#!/usr/bin/env python3
"""
TradingAgents 多股票并行分析工具

功能:
  - 支持多只股票或A股ETF并行分析
  - 5档分析强度 (1-闪电 ~ 5-极致)
  - 完整 CLI 参数支持
  - 自动市场检测 (A股/港股/美股)
  - 结果汇总与对比输出

用法示例:
  # 分析单只A股股票
  python analyze.py 000001

  # 分析单只A股ETF
  python analyze.py 159949 --asset-type etf

  # 自动识别股票/ETF（同一批次不能混合）
  python analyze.py 159949 --asset-type auto

  # 并行分析多只股票，强度3
  python analyze.py 000001 600519 00700 AAPL -l 3

  # 深度分析，指定日期
  python analyze.py 000001 600519 -l 5 -d 2025-03-17

  # 快速扫描，4线程并行
  python analyze.py 000001 600519 300750 601318 -l 1 -w 4
"""

import argparse
import json
import os
import sys
import time
import threading
import traceback
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from dotenv import load_dotenv

load_dotenv()

from rich.console import Console, Group
from rich.panel import Panel
from rich.table import Table
from rich.progress import (
    Progress,
    SpinnerColumn,
    TextColumn,
    BarColumn,
    TaskProgressColumn,
    TimeElapsedColumn,
    TimeRemainingColumn,
    MofNCompleteColumn,
)
from rich.live import Live
from rich.layout import Layout
from rich.text import Text
from rich import box
from rich.columns import Columns
from rich.align import Align

console = Console()


def _report_path_for(ticker: str, trade_date: str, config: Dict[str, Any]) -> Path:
    """Return the markdown report path generated by TradingAgentsGraph."""
    project_dir = Path(str(config.get("project_dir", ".")))
    return project_dir / "docs" / "reports" / f"{ticker}_{trade_date}_report.md"

# ─── 5 档分析强度定义 ────────────────────────────────────────────
# 每档对应不同的分析师组合、辩论轮数和递归限制
STOCK_INTENSITY_PROFILES = {
    1: {
        "name": "闪电",
        "desc": "极速扫描，最少分析师，单轮辩论",
        "analysts": ["market"],
        "max_debate_rounds": 1,
        "max_risk_discuss_rounds": 1,
        "max_recur_limit": 50,
    },
    2: {
        "name": "快速",
        "desc": "快速分析，核心分析师，单轮辩论",
        "analysts": ["market", "fundamentals"],
        "max_debate_rounds": 1,
        "max_risk_discuss_rounds": 1,
        "max_recur_limit": 80,
    },
    3: {
        "name": "标准",
        "desc": "均衡分析，三路分析师，双轮辩论",
        "analysts": ["market", "fundamentals", "news"],
        "max_debate_rounds": 2,
        "max_risk_discuss_rounds": 2,
        "max_recur_limit": 100,
    },
    4: {
        "name": "深度",
        "desc": "深度分析，全部分析师，三轮辩论",
        "analysts": ["market", "fundamentals", "news", "social"],
        "max_debate_rounds": 3,
        "max_risk_discuss_rounds": 3,
        "max_recur_limit": 150,
    },
    5: {
        "name": "极致",
        "desc": "最高精度，全部分析师，五轮辩论",
        "analysts": ["market", "fundamentals", "news", "social"],
        "max_debate_rounds": 5,
        "max_risk_discuss_rounds": 5,
        "max_recur_limit": 200,
    },
}

ETF_INTENSITY_PROFILES = {
    1: {
        "name": "ETF闪电",
        "desc": "极速扫描，ETF行情技术分析，单轮辩论",
        "analysts": ["market"],
        "max_debate_rounds": 1,
        "max_risk_discuss_rounds": 1,
        "max_recur_limit": 50,
    },
    2: {
        "name": "ETF快速",
        "desc": "快速分析，行情+产品结构，单轮辩论",
        "analysts": ["market", "product"],
        "max_debate_rounds": 1,
        "max_risk_discuss_rounds": 1,
        "max_recur_limit": 80,
    },
    3: {
        "name": "ETF标准",
        "desc": "均衡分析，行情+资金流+新闻+产品，双轮辩论",
        "analysts": ["market", "flow", "news", "product"],
        "max_debate_rounds": 2,
        "max_risk_discuss_rounds": 2,
        "max_recur_limit": 100,
    },
    4: {
        "name": "ETF深度",
        "desc": "深度分析，全部ETF分析师，三轮辩论",
        "analysts": ["market", "flow", "news", "product"],
        "max_debate_rounds": 3,
        "max_risk_discuss_rounds": 3,
        "max_recur_limit": 150,
    },
    5: {
        "name": "ETF极致",
        "desc": "最高精度，全部ETF分析师，五轮辩论",
        "analysts": ["market", "flow", "news", "product"],
        "max_debate_rounds": 5,
        "max_risk_discuss_rounds": 5,
        "max_recur_limit": 200,
    },
}

INTENSITY_PROFILES = STOCK_INTENSITY_PROFILES


def resolve_asset_type(tickers: List[str], requested: str = "stock") -> str:
    """Resolve CLI asset type, optionally detecting A-share ETFs."""
    normalized = (requested or "stock").lower()
    if normalized in {"stock", "etf"}:
        return normalized
    if normalized != "auto":
        raise ValueError(f"Unsupported asset type: {requested}")

    from tradingagents.dataflows.market_utils import detect_market, is_etf

    detected = []
    for ticker in tickers:
        asset_type = "etf" if detect_market(ticker) == "cn" and is_etf(ticker) else "stock"
        detected.append(asset_type)
    unique = set(detected)
    if len(unique) > 1:
        raise ValueError("auto asset type detected mixed stock and ETF tickers; run separate batches")
    return detected[0] if detected else "stock"


def resolve_intensity(args: argparse.Namespace) -> dict:
    """Return the intensity profile for the resolved asset type."""
    profiles = ETF_INTENSITY_PROFILES if getattr(args, "asset_type", "stock") == "etf" else STOCK_INTENSITY_PROFILES
    return profiles[args.level]


def build_config(args: argparse.Namespace, intensity: dict) -> Dict[str, Any]:
    """根据 CLI 参数和强度档位构建配置。"""
    from tradingagents.default_config import DEFAULT_CONFIG

    config = DEFAULT_CONFIG.copy()
    asset_type = getattr(args, "asset_type", "stock")
    config["asset_type"] = asset_type
    if asset_type == "etf":
        config["selected_etf_analysts"] = intensity["analysts"]

    # LLM 设置
    config["llm_provider"] = args.provider
    config["deep_think_llm"] = args.deep_model
    config["quick_think_llm"] = args.quick_model

    if args.backend_url:
        url = args.backend_url.rstrip("/")
        if not url.endswith("/v1"):
            url += "/v1"
        config["backend_url"] = url

    # 强度参数覆盖
    config["max_debate_rounds"] = intensity["max_debate_rounds"]
    config["max_risk_discuss_rounds"] = intensity["max_risk_discuss_rounds"]
    config["max_recur_limit"] = intensity["max_recur_limit"]

    # A股数据源
    if args.cn_vendor:
        config["cn_data_vendors"] = {
            "core_stock_apis": args.cn_vendor,
            "technical_indicators": args.cn_vendor,
            "fundamental_data": args.cn_vendor,
            "news_data": "akshare",
        }

    return config


def _was_date_explicitly_set(argv: List[str]) -> bool:
    """Return whether the user explicitly passed -d/--date."""
    for token in argv:
        if token in {"-d", "--date"} or token.startswith("--date="):
            return True
    return False


def _previous_weekday(date_str: str) -> str:
    """Roll back weekends to the previous weekday."""
    current = datetime.strptime(date_str, "%Y-%m-%d").date()
    while current.weekday() >= 5:
        current -= timedelta(days=1)
    return current.strftime("%Y-%m-%d")


def _resolve_cn_trade_date(date_str: str) -> str:
    """Resolve an A-share analysis date to the latest available trade date."""
    from tradingagents.dataflows.market_utils import get_cn_trade_dates

    current = datetime.strptime(date_str, "%Y-%m-%d").date()
    start = (current - timedelta(days=31)).strftime("%Y-%m-%d")
    end = current.strftime("%Y-%m-%d")

    try:
        trade_dates = get_cn_trade_dates(start, end)
    except Exception:
        return _previous_weekday(date_str)

    if not trade_dates:
        return _previous_weekday(date_str)

    return trade_dates[-1]


def resolve_analysis_date(
    tickers: List[str],
    requested_date: str,
    date_was_explicit: bool,
) -> Tuple[str, str]:
    """Resolve the effective analysis date for the current batch."""
    original_date = requested_date
    if date_was_explicit:
        return original_date, requested_date

    from tradingagents.dataflows.market_utils import detect_market

    markets = {detect_market(ticker) for ticker in tickers}
    if markets == {"cn"}:
        return original_date, _resolve_cn_trade_date(requested_date)

    return original_date, _previous_weekday(requested_date)


def _log(msg: str, ticker: str = "", style: str = ""):
    """带时间戳的日志输出。"""
    ts = datetime.now().strftime("%H:%M:%S")
    prefix = f"[dim]{ts}[/dim]"
    tag = f"[cyan]{ticker}[/cyan] " if ticker else ""
    if style:
        console.print(f"  {prefix} {tag}[{style}]{msg}[/{style}]")
    else:
        console.print(f"  {prefix} {tag}{msg}")


# ─── 阶段映射 ────────────────────────────────────────────────────
# 将 on_node 回调的 field 名映射到人类可读的阶段名和权重
# 权重用于进度条推进（总和在 analyze_single 中动态计算）
PHASE_MAP = {
    "market_report":            ("市场分析", 2),
    "sentiment_report":         ("情绪分析", 2),
    "news_report":              ("新闻分析", 2),
    "fundamentals_report":      ("基本面分析", 2),
    "china_market_report":      ("中国市场分析", 2),
    "etf_market_report":        ("ETF市场分析", 2),
    "etf_flow_report":          ("ETF资金流分析", 2),
    "etf_news_report":          ("ETF新闻分析", 2),
    "etf_product_report":       ("ETF产品分析", 2),
    "_inv_count":               ("投资辩论", 1),
    "investment_plan":          ("研究经理决策", 2),
    "trader_investment_plan":   ("交易员计划", 2),
    "_risk_count":              ("风险辩论", 1),
    "final_trade_decision":     ("最终决策", 3),
}


def _calc_total_steps(analysts: List[str], config: Dict[str, Any]) -> int:
    """根据分析师和辩论轮数估算总步数。"""
    if config.get("asset_type") == "etf":
        analyst_field_map = {
            "market": "etf_market_report",
            "flow": "etf_flow_report",
            "news": "etf_news_report",
            "product": "etf_product_report",
        }
    else:
        analyst_field_map = {
            "market": "market_report",
            "fundamentals": "fundamentals_report",
            "news": "news_report",
            "social": "sentiment_report",
            "china_market": "china_market_report",
        }
    steps = 0
    for a in analysts:
        field = analyst_field_map.get(a)
        if field and field in PHASE_MAP:
            steps += PHASE_MAP[field][1]
    # 辩论阶段: 每轮1步
    debate_rounds = config.get("max_debate_rounds", 1)
    risk_rounds = config.get("max_risk_discuss_rounds", 1)
    steps += debate_rounds * 2  # bull + bear 交替
    steps += risk_rounds * 3    # 三方风控辩论
    # 固定阶段: 研究经理 + 交易员 + 最终决策
    steps += PHASE_MAP["investment_plan"][1]
    steps += PHASE_MAP["trader_investment_plan"][1]
    steps += PHASE_MAP["final_trade_decision"][1]
    return max(steps, 1)


def analyze_single(
    ticker: str,
    trade_date: str,
    config: Dict[str, Any],
    analysts: List[str],
    debug: bool,
    log_fn=None,
    on_progress=None,
) -> Dict[str, Any]:
    """分析单只股票，返回结果字典。

    Args:
        on_progress: Optional callback ``fn(phase_name, weight)``
                     每当一个分析阶段推进时被调用。
    """
    from tradingagents.graph.trading_graph import TradingAgentsGraph
    from cli.stats_handler import StatsCallbackHandler

    log = log_fn or (lambda msg, **kw: _log(msg, ticker=ticker, **kw))
    t0 = time.time()
    result: Dict[str, Any] = {"ticker": ticker, "date": trade_date}

    try:
        stats = StatsCallbackHandler()

        log("初始化分析图 ...", style="yellow")
        ta = TradingAgentsGraph(
            selected_analysts=analysts,
            debug=debug,
            config=config,
            callbacks=[stats],
        )
        elapsed_init = round(time.time() - t0, 1)
        log(f"初始化完成 ({elapsed_init}s)，开始数据采集与分析 ...", style="green")

        # 节点回调：每个阶段推进时更新日志和进度
        seen_phases = set()

        def _on_node(field: str):
            phase_info = PHASE_MAP.get(field)
            if phase_info is None:
                return
            name, weight = phase_info
            # 对于辩论计数器，每次变化都记录（可多次）
            is_counter = field.startswith("_")
            if not is_counter:
                if field in seen_phases:
                    return
                seen_phases.add(field)
            elapsed = round(time.time() - t0, 1)
            log(f"[{elapsed}s] {name}", style="blue")
            if on_progress:
                on_progress(name, weight)

        final_state, decision = ta.propagate(ticker, trade_date, on_node=_on_node)

        st = stats.get_stats()
        result["status"] = "success"
        result["decision"] = decision
        result["elapsed"] = round(time.time() - t0, 1)
        result["stats"] = st
        report_path = _report_path_for(ticker, trade_date, config)
        result["report_path"] = str(report_path)
        result["report_exists"] = report_path.exists()
        result["report_lens"] = {
            "market_report": len(final_state.get("market_report", "")),
            "fundamentals_report": len(final_state.get("fundamentals_report", "")),
            "news_report": len(final_state.get("news_report", "")),
            "sentiment_report": len(final_state.get("sentiment_report", "")),
            "etf_market_report": len(final_state.get("etf_market_report", "")),
            "etf_flow_report": len(final_state.get("etf_flow_report", "")),
            "etf_news_report": len(final_state.get("etf_news_report", "")),
            "etf_product_report": len(final_state.get("etf_product_report", "")),
            "final_trade_decision": len(final_state.get("final_trade_decision", "")),
        }
        log(
            f"分析完成 — LLM调用: {st['llm_calls']}  工具调用: {st['tool_calls']}  "
            f"Token: {st['tokens_in']}↓ {st['tokens_out']}↑  耗时: {result['elapsed']}s",
            style="bold green",
        )
    except Exception as exc:
        result["status"] = "error"
        result["error"] = str(exc)
        result["traceback"] = traceback.format_exc()
        result["elapsed"] = round(time.time() - t0, 1)
        log(f"失败: {exc}", style="bold red")

    return result


# ─── 子进程入口 ──────────────────────────────────────────────────
def _worker(
    ticker: str,
    trade_date: str,
    config_json: str,
    analysts: List[str],
    debug: bool,
) -> Dict[str, Any]:
    """ProcessPoolExecutor 工作函数，接收 JSON 序列化的 config。"""
    load_dotenv()
    config = json.loads(config_json)
    return analyze_single(ticker, trade_date, config, analysts, debug)


def _serializable_config(config: Dict[str, Any]) -> str:
    """将 config 序列化为 JSON 字符串以便跨进程传递。"""
    clean = {}
    for k, v in config.items():
        try:
            json.dumps(v)
            clean[k] = v
        except (TypeError, ValueError):
            clean[k] = str(v)
    return json.dumps(clean, ensure_ascii=False)


# ─── 格式化工具 ──────────────────────────────────────────────────
def _fmt_tokens(n: int) -> str:
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    if n >= 1000:
        return f"{n / 1000:.1f}k"
    return str(n)


def _action_style(action: str) -> str:
    """为操作建议配色。"""
    a = str(action).strip()
    if a in ("买入", "buy", "Buy"):
        return "bold green"
    if a in ("卖出", "sell", "Sell"):
        return "bold red"
    return "bold yellow"


# ─── 输出格式化 ──────────────────────────────────────────────────
def print_header(args: argparse.Namespace, intensity: dict):
    """用 Rich Panel 打印分析任务头部信息。"""
    level_colors = {1: "cyan", 2: "green", 3: "yellow", 4: "magenta", 5: "red"}
    lv_color = level_colors.get(args.level, "white")
    original_date = getattr(args, "original_date", args.date)
    asset_label = "A股ETF" if getattr(args, "asset_type", "stock") == "etf" else "股票"

    info_lines = [
        f"[bold]{asset_label}列表[/bold]  : [cyan]{', '.join(args.tickers)}[/cyan]",
        f"[bold]资产类型[/bold]  : {asset_label}",
        f"[bold]分析日期[/bold]  : {original_date} -> {args.date}",
        f"[bold]分析强度[/bold]  : [{lv_color}]Lv.{args.level} {intensity['name']} — {intensity['desc']}[/{lv_color}]",
        f"[bold]分析师团队[/bold]: {', '.join(intensity['analysts'])}",
        f"[bold]辩论轮数[/bold]  : {intensity['max_debate_rounds']}   [bold]风控轮数[/bold]: {intensity['max_risk_discuss_rounds']}",
        f"[bold]并行进程[/bold]  : {args.workers}",
        f"[bold]LLM[/bold]       : {args.provider} / {args.quick_model}",
    ]
    panel = Panel(
        "\n".join(info_lines),
        title="[bold]TradingAgents 股票/ETF分析工具[/bold]",
        subtitle=f"共 {len(args.tickers)} 个标的",
        border_style="blue",
        padding=(1, 2),
    )
    console.print(panel)
    console.print()


def print_result(result: Dict[str, Any], idx: int, total: int):
    """用 Rich 打印单只股票的结果摘要。"""
    ticker = result["ticker"]

    if result["status"] == "error":
        console.print(
            f"  [bold red]✗[/bold red] [{idx}/{total}] "
            f"[cyan]{ticker}[/cyan] — [red]失败[/red] ({result['elapsed']}s)"
        )
        console.print(f"    [dim red]{result['error']}[/dim red]")
        return

    d = result["decision"]
    action = d.get("action", "N/A")
    astyle = _action_style(action)
    conf = d.get("confidence")
    conf_str = f"{conf:.0%}" if isinstance(conf, (int, float)) else str(conf or "-")
    risk = d.get("risk_score")
    risk_str = f"{risk:.0%}" if isinstance(risk, (int, float)) else str(risk or "-")

    console.print(
        f"  [bold green]✓[/bold green] [{idx}/{total}] "
        f"[cyan]{ticker}[/cyan] — [{astyle}]{action}[/{astyle}]  "
        f"目标价: {d.get('target_price', '-')}  "
        f"置信度: {conf_str}  风险: {risk_str}  "
        f"[dim]({result['elapsed']}s)[/dim]"
    )
    reason = str(d.get("reasoning", ""))
    if len(reason) > 150:
        reason = reason[:150] + "…"
    console.print(f"    [dim]{reason}[/dim]")

    # 展示 stats
    st = result.get("stats")
    if st:
        console.print(
            f"    [dim]LLM: {st['llm_calls']}次  "
            f"工具: {st['tool_calls']}次  "
            f"Token: {_fmt_tokens(st['tokens_in'])}↓ {_fmt_tokens(st['tokens_out'])}↑[/dim]"
        )
    report_path = result.get("report_path")
    if report_path:
        if result.get("report_exists"):
            console.print(f"    [dim]完整报告: {report_path}[/dim]")
        else:
            console.print(f"    [yellow]完整报告未找到: {report_path}[/yellow]")


def print_summary(results: List[Dict[str, Any]]):
    """用 Rich Table 打印最终汇总表。"""
    console.print()

    # ── 决策汇总表 ──
    table = Table(
        title="分析汇总",
        box=box.ROUNDED,
        show_lines=True,
        header_style="bold magenta",
        title_style="bold",
        padding=(0, 1),
    )
    table.add_column("股票", style="cyan", justify="center", width=10)
    table.add_column("操作", justify="center", width=8)
    table.add_column("目标价", justify="right", width=12)
    table.add_column("置信度", justify="center", width=8)
    table.add_column("风险", justify="center", width=8)
    table.add_column("LLM次", justify="right", width=7)
    table.add_column("工具次", justify="right", width=7)
    table.add_column("Token↓", justify="right", width=8)
    table.add_column("Token↑", justify="right", width=8)
    table.add_column("耗时", justify="right", width=8)

    success = [r for r in results if r["status"] == "success"]
    failed = [r for r in results if r["status"] == "error"]

    for r in success:
        d = r["decision"]
        action = str(d.get("action", "-"))
        astyle = _action_style(action)
        price = str(d.get("target_price", "-"))
        conf = d.get("confidence")
        conf_str = f"{conf:.0%}" if isinstance(conf, (int, float)) else str(conf or "-")
        risk = d.get("risk_score")
        risk_str = f"{risk:.0%}" if isinstance(risk, (int, float)) else str(risk or "-")
        st = r.get("stats", {})
        table.add_row(
            r["ticker"],
            f"[{astyle}]{action}[/{astyle}]",
            price,
            conf_str,
            risk_str,
            str(st.get("llm_calls", "-")),
            str(st.get("tool_calls", "-")),
            _fmt_tokens(st.get("tokens_in", 0)),
            _fmt_tokens(st.get("tokens_out", 0)),
            f"{r['elapsed']}s",
        )

    for r in failed:
        table.add_row(
            r["ticker"],
            "[red]失败[/red]",
            "-", "-", "-", "-", "-", "-", "-",
            f"{r['elapsed']}s",
        )

    console.print(table)

    # ── 统计行 ──
    total_time = sum(r["elapsed"] for r in results)
    total_llm = sum(r.get("stats", {}).get("llm_calls", 0) for r in success)
    total_tool = sum(r.get("stats", {}).get("tool_calls", 0) for r in success)
    total_in = sum(r.get("stats", {}).get("tokens_in", 0) for r in success)
    total_out = sum(r.get("stats", {}).get("tokens_out", 0) for r in success)
    console.print(
        f"  [bold]成功: {len(success)}/{len(results)}[/bold]  |  "
        f"LLM: {total_llm}次  工具: {total_tool}次  "
        f"Token: {_fmt_tokens(total_in)}↓ {_fmt_tokens(total_out)}↑  |  "
        f"总耗时: [bold]{total_time:.1f}s[/bold]"
    )
    if success:
        console.print("  [bold]完整 Markdown 报告:[/bold]")
        for r in success:
            report_path = r.get("report_path")
            if not report_path:
                continue
            marker = "✓" if r.get("report_exists") else "!"
            style = "dim" if r.get("report_exists") else "yellow"
            console.print(f"  [{style}]{marker} {r['ticker']}: {report_path}[/{style}]")

    # ── 保存汇总 JSON ──
    summary_dir = Path("eval_results/_batch_summary")
    summary_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    summary_file = summary_dir / f"batch_{ts}.json"
    with open(summary_file, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2, default=str)
    console.print(f"  [dim]汇总已保存: {summary_file}[/dim]")
    console.print()


# ─── CLI 定义 ────────────────────────────────────────────────────
def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    argv_list = list(argv) if argv is not None else sys.argv[1:]
    parser = argparse.ArgumentParser(
        prog="analyze",
        description="TradingAgents 股票/ETF并行分析工具",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
分析强度档位:
  股票模式:
    1  闪电  极速扫描，市场分析师，单轮辩论
    2  快速  核心双分析师（市场+基本面），单轮辩论
    3  标准  三路分析师（+新闻），双轮辩论
    4  深度  全部分析师，三轮辩论
    5  极致  全部分析师，五轮辩论
  ETF模式:
    1  ETF闪电  行情技术分析
    2  ETF快速  行情+产品结构
    3+ ETF标准  行情+资金流+新闻+产品

示例:
  %(prog)s 000001                                  # A股股票，默认强度2
  %(prog)s 000001 600519 -l 4                      # 两只A股股票，深度分析
  %(prog)s AAPL MSFT GOOGL -l 3 -w 3               # 三只美股并行
  %(prog)s 159949 --asset-type etf -l 3            # A股ETF完整分析
  %(prog)s 159949 --asset-type auto                # 自动识别ETF
  %(prog)s 000001 -l 5 -d 2025-03-17               # 极致分析，指定日期
""",
    )

    parser.add_argument(
        "tickers",
        nargs="+",
        help="股票或ETF代码列表（空格分隔）；ETF模式仅支持A股场内ETF",
    )
    parser.add_argument(
        "--asset-type",
        choices=["stock", "etf", "auto"],
        default="stock",
        help="资产类型：stock股票、etf A股ETF、auto自动识别（默认: stock）",
    )
    parser.add_argument(
        "-l", "--level",
        type=int,
        choices=[1, 2, 3, 4, 5],
        default=2,
        help="分析强度 1-5（默认: 2）",
    )
    parser.add_argument(
        "-d", "--date",
        type=str,
        default=date.today().strftime("%Y-%m-%d"),
        help="分析日期 YYYY-MM-DD（默认: 今天）",
    )
    parser.add_argument(
        "-w", "--workers",
        type=int,
        default=1,
        help="并行进程数（默认: 1，即串行）",
    )
    parser.add_argument(
        "--provider",
        type=str,
        default=os.getenv("LLM_PROVIDER", "deepseek"),
        help="LLM 提供商（默认: deepseek）",
    )
    parser.add_argument(
        "--deep-model",
        type=str,
        default=os.getenv("DEEP_LLM_MODEL", os.getenv("CUSTOM_LLM_MODEL", "deepseek-v4-flash")),
        help="深度思考模型名",
    )
    parser.add_argument(
        "--quick-model",
        type=str,
        default=os.getenv("QUICK_LLM_MODEL", os.getenv("CUSTOM_LLM_MODEL", "deepseek-v4-flash")),
        help="快速思考模型名",
    )
    parser.add_argument(
        "--backend-url",
        type=str,
        default=os.getenv("CUSTOM_LLM_API_URL", ""),
        help="LLM API 地址",
    )
    parser.add_argument(
        "--cn-vendor",
        type=str,
        choices=["tushare", "akshare", "baostock"],
        default="tushare",
        help="A股数据源（默认: tushare）",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="开启调试模式（打印详细 LLM 交互日志）",
    )

    args = parser.parse_args(argv_list)
    args.date_was_explicit = _was_date_explicitly_set(argv_list)
    args.asset_type = resolve_asset_type(args.tickers, args.asset_type)
    return args


# ─── 进度条工厂 ──────────────────────────────────────────────────
def _make_batch_progress() -> Progress:
    """创建批量总进度条。"""
    return Progress(
        SpinnerColumn("earth"),
        TextColumn("[bold]总进度"),
        BarColumn(bar_width=30, complete_style="green", finished_style="bold green"),
        MofNCompleteColumn(),
        TextColumn("•"),
        TimeElapsedColumn(),
        TextColumn("•"),
        TimeRemainingColumn(),
    )


def _make_stock_progress() -> Progress:
    """创建每只股票的细粒度进度条。"""
    return Progress(
        SpinnerColumn("dots"),
        TextColumn("[bold blue]{task.fields[ticker]:>8}"),
        BarColumn(bar_width=24, complete_style="green"),
        TaskProgressColumn(),
        TextColumn("•"),
        TimeElapsedColumn(),
        TextColumn("•"),
        TextColumn("{task.fields[phase]}"),
    )


def _warn_if_market_open(trade_date: str, tickers: list):
    """Warn user if analyzing A-share tickers while market data may be incomplete.

    tushare/akshare daily data is only available after market close (~16:00 CST).
    Running analysis during trading hours will result in missing current-day data.
    """
    from tradingagents.dataflows.market_utils import detect_market

    today_str = date.today().strftime("%Y-%m-%d")
    if trade_date != today_str:
        return

    has_cn = any(detect_market(t) == "cn" for t in tickers)
    if not has_cn:
        return

    now_hour = datetime.now().hour
    if now_hour < 16:
        console.print(
            Panel(
                "[yellow]检测到分析日期为今天，且包含A股标的。\n"
                "A股日线数据通常在收盘后（~16:00）才发布。\n"
                "当前时间早于 16:00，今日行情数据可能尚未生成，系统将自动使用最近交易日的数据。[/yellow]",
                title="[bold yellow]⚠ 盘中数据提醒[/bold yellow]",
                border_style="yellow",
            )
        )


# ─── 主入口 ──────────────────────────────────────────────────────
def main(argv: Optional[List[str]] = None):
    args = parse_args(argv)
    args.original_date, args.date = resolve_analysis_date(
        tickers=args.tickers,
        requested_date=args.date,
        date_was_explicit=args.date_was_explicit,
    )
    intensity = resolve_intensity(args)
    config = build_config(args, intensity)
    analysts = intensity["analysts"]

    print_header(args, intensity)

    tickers = args.tickers

    # ── 盘中运行警告 ──
    _warn_if_market_open(args.date, tickers)
    results: List[Dict[str, Any]] = []
    batch_t0 = time.time()
    total_steps_per_stock = _calc_total_steps(analysts, config)

    if len(tickers) == 1 or args.workers <= 1:
        # ── 串行执行（带逐条进度条）──
        batch_progress = _make_batch_progress()
        batch_task = batch_progress.add_task("batch", total=len(tickers))

        stock_progress = _make_stock_progress()

        for i, ticker in enumerate(tickers, 1):
            console.rule(f"[bold cyan]{ticker}[/bold cyan]  ({i}/{len(tickers)})")
            _log("开始分析 ...", ticker=ticker, style="bold blue")

            # 每只股票一个细粒度进度条任务
            stask = stock_progress.add_task(
                ticker, total=total_steps_per_stock, ticker=ticker, phase="初始化"
            )

            def _on_progress(phase_name, weight, _stask=stask):
                stock_progress.update(_stask, advance=weight, phase=phase_name)

            # 用 Group+Live 同时展示总进度和当前股票进度
            progress_group = Group(batch_progress, stock_progress)
            with Live(progress_group, console=console, refresh_per_second=4, transient=True):
                result = analyze_single(
                    ticker, args.date, config, analysts, args.debug,
                    on_progress=_on_progress,
                )

            # Live 退出后，把进度条最终状态补齐然后显示结果
            stock_progress.update(stask, completed=total_steps_per_stock, phase="[green]完成[/green]")
            results.append(result)
            print_result(result, i, len(tickers))
            console.print()
            batch_progress.update(batch_task, advance=1)

        console.print(batch_progress)
    else:
        # ── 并行执行（带总进度条 + 每股状态）──
        # 注：跨进程无法传递回调，并行模式使用每股完成级别的刷新
        max_w = min(args.workers, len(tickers))
        console.print(f"  [bold]启动 {max_w} 个并行进程 ...[/bold]\n")
        config_json = _serializable_config(config)

        batch_progress = _make_batch_progress()
        batch_task = batch_progress.add_task("batch", total=len(tickers))

        stock_tasks: Dict[str, Any] = {}
        stock_progress = _make_stock_progress()
        for t in tickers:
            tid = stock_progress.add_task(
                t, total=total_steps_per_stock, ticker=t, phase="排队中"
            )
            stock_tasks[t] = tid

        progress_group = Group(batch_progress, stock_progress)

        with Live(progress_group, console=console, refresh_per_second=4):
            with ProcessPoolExecutor(max_workers=max_w) as pool:
                future_map = {
                    pool.submit(_worker, t, args.date, config_json, analysts, args.debug): t
                    for t in tickers
                }

                for fut, t in future_map.items():
                    stock_progress.update(stock_tasks[t], phase="[yellow]分析中 ...[/yellow]")

                done_count = 0
                for future in as_completed(future_map):
                    done_count += 1
                    t = future_map[future]
                    result = future.result()
                    results.append(result)

                    if result["status"] == "success":
                        action = result["decision"].get("action", "")
                        phase_text = f"[green]✓ {action}[/green]"
                    else:
                        phase_text = "[red]✗ 失败[/red]"
                    stock_progress.update(
                        stock_tasks[t],
                        completed=total_steps_per_stock,
                        phase=phase_text,
                    )
                    batch_progress.update(batch_task, advance=1)

        # 打印每条结果
        console.print()
        for i, r in enumerate(results, 1):
            print_result(r, i, len(tickers))
            console.print()

    # 按原始顺序排序结果
    order = {t: i for i, t in enumerate(tickers)}
    results.sort(key=lambda r: order.get(r["ticker"], 999))

    total_wall = round(time.time() - batch_t0, 1)
    print_summary(results)
    console.print(f"  [dim]总墙钟时间: {total_wall}s[/dim]")

    # 退出码: 有失败则返回 1
    if any(r["status"] == "error" for r in results):
        sys.exit(1)


if __name__ == "__main__":
    main()
