from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    asset_type: Annotated[str, "Asset type: stock or etf"]
    analysis_mode: Annotated[str, "Analysis mode such as hybrid"]
    market_context: Annotated[dict, "Market context (market, exchange, currency, language)"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    china_market_report: Annotated[str, "Report from the China Market Analyst"]
    etf_market_report: Annotated[str, "Report from the ETF Market Analyst"]
    etf_product_report: Annotated[str, "Report from the ETF Product Analyst"]
    etf_news_report: Annotated[str, "Report from the ETF News Analyst"]
    etf_flow_report: Annotated[str, "Report from the ETF Flow Analyst"]

    # Tool call counters (death-loop prevention)
    market_tool_call_count: Annotated[int, "Number of tool calls by Market Analyst"]
    sentiment_tool_call_count: Annotated[int, "Number of tool calls by Social Media Analyst"]
    news_tool_call_count: Annotated[int, "Number of tool calls by News Analyst"]
    fundamentals_tool_call_count: Annotated[int, "Number of tool calls by Fundamentals Analyst"]
    china_market_tool_call_count: Annotated[int, "Number of tool calls by China Market Analyst"]
    flow_tool_call_count: Annotated[int, "Number of tool calls by ETF Flow Analyst"]
    product_tool_call_count: Annotated[int, "Number of tool calls by ETF Product Analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]


ETF_GENERIC_REPORT_MAP = {
    "etf_market_report": "market_report",
    "etf_product_report": "fundamentals_report",
    "etf_news_report": "news_report",
    "etf_flow_report": "sentiment_report",
}


def apply_asset_report_mapping(update: dict, asset_type: str) -> dict:
    """Populate generic downstream report slots from asset-specific ETF fields."""
    mapped = dict(update)
    if asset_type != "etf":
        return mapped

    for etf_field, generic_field in ETF_GENERIC_REPORT_MAP.items():
        content = mapped.get(etf_field)
        if content is not None and generic_field not in mapped:
            mapped[generic_field] = content

    return mapped
